State
ErdunE/CS5010-The-State-Pattern-in-Chess pull request #7
Opened 2024-10-31 14:53 UTC by xinyuhwang

Added commoms package under states
Added Move class in commons package
Updated State class

2024-10-31 14:57 UTC, ErdunE commented on ChessStatePattern/src/states/State.java
Blank line, is not necessary.

2024-10-31 15:01 UTC, ErdunE commented on ChessStatePattern/src/states/State.java
We need a Javadoc comment

2024-10-31 15:32 UTC, ErdunE reviewed
Summary：
1. Optimize the PR's title and description with more clear clarification of the changes.
2. Consider moving `moveHistory` to `ChessGame` for centralized management. In this way, each state can access and update a global move record instead of holding its own separate history.
3. Add edges conditions in the Move constructor to ensure each move represents a valid board position.
4. Adding comments on key methods to describe their purpose and usage will make the code clearer for other classmates

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/State.java
> +
Javadoc comment is needed

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/State.java
> +	public String getActivePlayer() {
Javadoc comment is needed

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/State.java
> +	public void addMove(Move move) {
Javadoc comment is needed

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/State.java
> +	public List<Move> getMoveHistory() {
Javadoc comment is needed

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/State.java
> +	String activePlayer;
Seems like you added `activePlayer` there and plan to track each player's actions,
but we need to ensure that each time switch the player action, this `activePlayer` needs to be updated. Will it be implemented in `setActivePlayer `?

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/State.java
Blank line, is not necessary.

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/State.java
> +
Blank line, is not necessary.

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/State.java
We need a Javadoc comment

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/State.java
> +	List<Move> moveHistory;
In the state pattern, each state’s primary role is to define behavior, not to store or manage cross-state data. ChessGame as the main controller manages game-wide data, while state classes focus on defining state-specific behavior.

In this case, what do you think about moving this to ChessGame?

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/State.java
> -	//here is where you write the methods you will want overridden by each
Based on the professor provided hints, 
Which methods planned to be overridden by each specific state's behavior?

In my option, such as, `isGameOver`, `takeTurn`, etc?

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/State.java
>  package states;
Left comments right here,

The PR title need to be modified that clear to appear what's the pr about, not only 'state'
For example, it's related to State class and Move class, the title should mention what's change/add/modify on them.

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/commons/Move.java
> +
javadoc comment

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/commons/Move.java
> +    public Move(int row, int col) {
Just a discuss that
I was thinking if there need to set up edges condition and throw exception due to the board is 8 X 8
it's like once  0 > row or 7 < row or 0 > col or 7 < col

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/commons/Move.java
> +    public void setRow(int row) {
javadoc comment

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/commons/Move.java
> +    public void setCol(int col) {
javadoc comment

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/commons/Move.java
> +    public int getRow() {
javadoc comment

2024-10-31 15:32 UTC, ErdunE commented on ChessStatePattern/src/states/commons/Move.java
> +    public int getCol() {
javadoc comment

2024-11-03 03:14 UTC, arete7-kai approved these changes

2024-11-03 03:14 UTC, arete7-kai submitted a review, later dismissed

2024-11-03 20:01 UTC, ErdunE requested changes
Looks good to me overall, but I noticed a few minor changes that could improve clearer. Here’s a summary:

### Summary:
1. Rename `check` and `checkMate` to `isCheck` and `isCheckmate` for clarity, as they are boolean states.
2. Rename `setEscape()` to `clearCheck()` or `setNormalPlay()` for clearer indication of its function to cancel the “Check” state.
3. Optimize the PR title to better reflect its content.
4. Add a summary of class changes and optimizations in the PR description.

2024-11-03 20:01 UTC, ErdunE commented on ChessStatePattern/src/states/State.java
> +	private boolean checkMate;
`check` and `checkMate` the name make a bit confusing to use, due to they are only the states of boolean.
Suggest rename it as `isCheck` and `isCheckmate` for clarity

2024-11-03 20:01 UTC, ErdunE commented on ChessStatePattern/src/states/State.java
> +	public void setEscape() {
The method name `setEscape()` is not quite clear enough to immediately see that its function is to cancel the  "Check" state. 
Consider changing it to `clearCheck()` or `setNormalPlay()` to express its function more clearly.

2024-11-05 16:50 UTC, NEUNaveen approved these changes

2024-11-05 16:52 UTC, NEUNaveen approved these changes, later dismissed

2024-11-06 02:14 UTC, ErdunE approved these changes
Worked with Kai and Hailee in Zoom meeting together, and we all approved this after discussed

2024-11-06 02:14 UTC, merged